### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [ecomclub/storage-api#1]
Greetings, 

I'm a graphic designer and I like contributing to open source projects. I would love to make a logo for yours, for free. Please let me know if you are interested, if yes I will ask you a few questions for the logo to fit great in your project.

Miguel Medina, michaelizer.
Best regards.

**Comment by leomp12** [comment]
Hello Miguel,
It sounds really good! Waiting for your questions, thank you.

**Comment by michaelizer** [comment]
Glad you agree, the questions are:

- What name should be displayed in the logo? if there should be any.
- What's the purpose of the project, what is it intended to do?
- What would you like the logo to transmit?

Looking forward to your reply :))

**Comment by leomp12** [comment]
Hello again Miguel, sorry for the delay.

- "Storage API", but it's not necessary, you can judge if the logo will be better with or without text;
- REST API for file uploads and objects CRUD with Digital Ocean Spaces and AWS S3 SDK;
- The API is modern (trending technologies), simple and easy to use;

Thanks!

**Comment by michaelizer** [comment]
Hello again, sorry for the delay. What do you think about these sketches
![imagen](https://user-images.githubusercontent.com/35619342/42475030-67e0fe2c-8397-11e8-9c3d-85ed1c6003bb.png)

**Comment by leomp12** [comment]
I've liked so much the first, but I think it will be better without the colored background.
The last is also very great, I'm in doubt with them.

**Comment by michaelizer** [comment]
What about these?
![1recurso_2](https://user-images.githubusercontent.com/35619342/42489118-3575b3e8-83d7-11e8-93fb-026108c9c243.png)

**Comment by leomp12** [comment]
I think the better is the last blue logo (fifth) :+1: 
Can you send it to me in a PNG file?
Thanks!

**Comment by michaelizer** [comment]
Done ([#2](https://github.com/ecomclub/storage-api/pull/2))!. It was a real pleasure :)

**Comment by leomp12** [comment]
Great!
