### ISSUE TITLE
Credentials exposed?

### ISSUE THREAD

**Issue by mondaysunrise** [ecomclub/storage-api#12]
https://github.com/ecomplus/storage-api/blob/7533d1c9d4b666b6b2b3a3d68e137240dd3da498/config/config-sample.json#L7

Hi there,

please remove your exposed credentials from your Git repository commit history, change them and externalize.

Cheers,

**Comment by leomp12** [comment]
Hey,
You mean _abcdefgh_ ? It's not a valid key id, just a random string 😄

**Comment by mondaysunrise** [comment]
Perfect!
