### ISSUE TITLE
Erro ao subir imagem webp (Biblioteca)

### ISSUE THREAD

**Issue by leomp12** [ecomclub/storage-api#4]
https://github.com/ecomclub/ecomplus-admin/issues/77

**Comment by leomp12** [comment]
@eduvlemes o problema é que não temos como redimensionar WebP (limitação do [Kraken](https://kraken.io/)).

O correto é você fazer o upload de imagens JPG/PNG para que a Storage API faça o redimensionamento para os 4 tamanhos de usamos, em seguida serão parseadas para WebP.

Então no fim das contas você terá as imagens em WebP, com as variações de dimensões e com uma versão em JPG/PNG que será usada em navegadores sem suporte para WebP (Safari), acho que este é o cenário ideal.

Acho que isto não é exatamente um bug, mas o que posso fazer é aceitar o upload de WebP direto mas não redimensionar neste caso, mas sendo assim sempre será carregada a imagem em tamanho original, teria um efeito ruim em performance.

O que acham @eduvlemes @matheusgnreis ?

**Comment by matheusgnreis** [comment]
Acredito que a melhor solução seja a primeira informada, devido a performance. Uma vez que se o lojista puder inserir WebP e mantiver apenas um tamanho, no checkout mesmo, que deve aparecer um thumbnail com tamanho bem inferior, logo menor carregamento, iria aparecer uma imagem com um tamanho desnecessário para essa aplicação. Assim como, em outras aplicações ou dispositivos que não necessitam de uma imagem grande. Logo, o ideal é ter mesmo diversos tamanhos das imagens WebP a partir do upload de imagens JPG/PNG.
